apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-service
spec:
  type: NodePort
  selector:
    app: sentiment-api
    slot: blue
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32500
